name: Trigger rebuild from Contentful

on:
  repository_dispatch:
    types: [contentful_update]

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create empty commit
        run: |
          git config user.name "actions"
          git config user.email "134336066+b3nkang@users.noreply.github.com"
          git commit --allow-empty -m "contentful rebuild"
          git push
